Repository GSG-G13/Nour-Alaa, pull requests merged in 2023-04, with the labels that each got.

#3 fix files
  .gitignore
  public/.gitkeep
  server/controlers/.gitkeep
  server/dataBase/.gitkeep
  server/routers/.gitkeep
Labels: documentation

#6 add app,routerand errors
  .env
  .eslintrc.json
  .gitignore
  node_modules/.bin/browserslist
  node_modules/.bin/browserslist-lint
  node_modules/.bin/esparse
  node_modules/.bin/esvalidate
  node_modules/.bin/import-local-fixture
  node_modules/.bin/jest
  node_modules/.bin/js-yaml
  node_modules/.bin/jsesc
  node_modules/.bin/json5
  node_modules/.bin/mime
  node_modules/.bin/node-which
  node_modules/.bin/nodemon
  node_modules/.bin/nodetouch
  node_modules/.bin/nopt
  node_modules/.bin/parser
  node_modules/.bin/resolve
  node_modules/.bin/semver
  node_modules/.package-lock.json
  node_modules/jest-snapshot/node_modules/.bin/semver
  node_modules/nodemon/node_modules/.bin/semver
  node_modules/simple-update-notifier/node_modules/.bin/semver
  node_modules/superagent/node_modules/.bin/semver
  package-lock.json
  package.json
  server/app.js
  server/controlers/errors/error.js
  server/routers/router.js
Labels: approve

#14 Create connection
  server/dataBase/connection/connection.js
  server/dataBase/connection/index.js
Labels: approve

#15 create getData query to get all data from database
  server/dataBase/index.js
  server/dataBase/query/getDataQuery.js
  server/dataBase/query/index.js
Labels: approve

#17 create home router in server
  server/controlers/errors/error.js
  server/dataBase/index.js
  server/dataBase/query/getDataQuery.js
  server/dataBase/query/index.js
  server/routers/middleware/getData.js
  server/routers/middleware/index.js
  server/routers/router.js
Labels: approve

#19 create post methods, post query , and handle server endpoint
  server/dataBase/config/bild.sql
  server/dataBase/index.js
  server/dataBase/query/index.js
  server/dataBase/query/postDataQuery.js
  server/routers/middleware/getData.js
  server/routers/middleware/index.js
  server/routers/middleware/postprouduct.js
  server/routers/router.js
Labels: approve

#25 add public with fetch
  public/js/admin.js
Labels: approve

#27 fix fetch
  public/css/user.css
  public/html/admin.html
  public/html/user.html
  public/js/admin.js
  public/js/login.js
  public/js/user.js
  server/controlers/errors/error.js
  server/dataBase/config/bild.sql
  server/routers/middleware/postprouduct.js
  server/routers/router.js
Labels: approve

#30 add the delete router, query
  server/dataBase/query/deletequery.js
  server/routers/middleware/deletmeddil.js
  server/routers/router.js
Labels: approve

#32 31 add delete fetch
  public/js/admin.js
  server/routers/router.js
Labels: approve

#33 fix delete router
  public/css/admin.css
  public/html/admin.html
  public/html/user.html
  public/js/admin.js
  server/dataBase/connection/connection.js
  server/dataBase/query/getDataQuery.js
  server/dataBase/query/postDataQuery.js
  server/routers/middleware/postprouduct.js
Labels: waiting review
